/**
 * This file was generated by the Jeddict
 */
package com.udea.inventario2024.com.udea.inventario2024.entity;

import java.util.Date;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.PastOrPresent;
import javax.validation.constraints.PositiveOrZero;

/**
 * @author Diego
 */
@Entity(name = "Producto")
@IdClass(ProductoPK.class)

public class Producto {

    @Column(name = "id", unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false)
    @Basic
    private String nombreProducto;

    @Column(nullable = false)
    @Basic
    @PositiveOrZero(message = "Debe ingresar valores positivos")
    private int cantidadDisponible;

    @Column(nullable = false)
    @Basic
    @PositiveOrZero(message = "Debe ingresar un precio valido")
    private double precio;

    @Column(nullable = false)
    @Basic
    @Temporal(TemporalType.DATE)
    @PastOrPresent(message = "Revise la fecha")
    private Date fechaIngreso;

    @Id
    @ManyToOne
    private TipoProducto tipoProducto;

    public Producto(Long id, String nombreProducto, int cantidadDisponible, double precio, Date fechaIngreso, TipoProducto tipoProducto) {
        this.id = id;
        this.nombreProducto = nombreProducto;
        this.cantidadDisponible = cantidadDisponible;
        this.precio = precio;
        this.fechaIngreso = fechaIngreso;
        this.tipoProducto = tipoProducto;
    }

    public Producto() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombreProducto() {
        return this.nombreProducto;
    }

    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    public int getCantidadDisponible() {
        return this.cantidadDisponible;
    }

    public void setCantidadDisponible(int cantidadDisponible) {
        this.cantidadDisponible = cantidadDisponible;
    }

    public double getPrecio() {
        return this.precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }

    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Producto other = (Producto) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public String toString() {
        return "Producto{" + " id=" + id + ", nombreProducto=" + nombreProducto + ", cantidadDisponible=" + cantidadDisponible + ", precio=" + precio + ", fechaIngreso=" + fechaIngreso + ", tipoProducto=" + tipoProducto + '}';
    }

}