/**
 * This file was generated by the Jeddict
 */
package com.udea.inventario2024.com.udea.inventario2024.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

/**
 * @author Diego
 */
@Entity(name = "TipoProducto")
public class TipoProducto {

    @Column(name = "id", unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "tipoProducto", nullable = false)
    @Basic
    private String tipoProducto;

    @OneToMany(mappedBy = "tipoProducto")
    private List<Producto> productoes;

    public TipoProducto(Long id, String tipoProducto, List<Producto> productoes) {
        this.id = id;
        this.tipoProducto = tipoProducto;
        this.productoes = productoes;
    }

    public TipoProducto() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTipoProducto() {
        return this.tipoProducto;
    }

    public void setTipoProducto(String tipoProducto) {
        this.tipoProducto = tipoProducto;
    }

    public List<Producto> getProductoes() {
        if (productoes == null) {
            productoes = new ArrayList<>();
        }
        return this.productoes;
    }

    public void setProductoes(List<Producto> productoes) {
        this.productoes = productoes;
    }

    public void addProducto(Producto producto) {
        getProductoes().add(producto);
        producto.setTipoProducto(this);
    }

    public void removeProducto(Producto producto) {
        getProductoes().remove(producto);
        producto.setTipoProducto(null);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final TipoProducto other = (TipoProducto) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public String toString() {
        return id + "----" + tipoProducto ;
    }

}